import {
  PROMPT_MONSTERS_EXTERNAL_LINK,
  MOCK_ERC20_ADDRESS,
  PROMPT_MONSTERS_WALLET,
  MINT_PRICE,
} from "../const";

module.exports = [
  PROMPT_MONSTERS_EXTERNAL_LINK,
  MOCK_ERC20_ADDRESS,
  MINT_PRICE,
  PROMPT_MONSTERS_WALLET,
];
